# Generated by Django 3.0.12 on 2021-04-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='URL'),
        ),
    ]
