# Generated by Django 3.0.12 on 2021-03-10 20:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foodstuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, default='_', max_length=250, verbose_name='Ingredient')),
                ('form', models.CharField(choices=[('TIN', 'Tinned'), ('FRZ', 'Frozen'), ('FRS', 'Fresh'), ('RAW', 'Raw'), ('CKD', 'Cooked'), ('POR', 'Portion'), ('CHP', 'Chopped'), ('DRY', 'Dried'), ('WRM', 'Warm'), ('CLD', 'Cold'), ('DCD', 'Diced'), ('SLC', 'Sliced'), ('MLT', 'Melted'), ('NON', '_')], default='NON', max_length=3, verbose_name='Form')),
                ('foodstuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Foodstuff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngredientList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Quantity')),
                ('uom', models.CharField(choices=[('GRM', 'Gram'), ('KGM', 'Kilogram'), ('MLT', 'Millilitre'), ('LTR', 'Litre'), ('TSP', 'Tea Spoon'), ('TBS', 'Table Spoon'), ('DSP', 'Dessert Spoon'), ('UNT', 'Unit'), ('POR', 'Portion'), ('SPL', 'Splash'), ('TST', 'To Taste'), ('HND', 'Handful'), ('NON', '_')], default='NON', max_length=3, verbose_name='Unit of Measure')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingredient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=250, verbose_name='Name of Recipe')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('method', models.TextField(blank=True, verbose_name='Method')),
                ('tag', models.CharField(blank=True, default='none, ', max_length=100, verbose_name='Tag')),
                ('serves', models.IntegerField(default=0, verbose_name='Serves')),
                ('prep', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Prep (mins)')),
                ('cook', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Cook (mins)')),
                ('slug', models.SlugField(default='_', unique=True)),
                ('ingredients', models.ManyToManyField(related_name='ingredient', through='recipes.IngredientList', to='recipes.Ingredient')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='ingredientlist',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe'),
        ),
        migrations.CreateModel(
            name='CookBookList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('page', models.IntegerField(default=0, verbose_name='Page No.')),
                ('url', models.URLField(blank=True, default='', null=True, verbose_name='URL')),
                ('cookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
