# Generated by Django 3.0.12 on 2021-02-25 13:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foodstuff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('form', models.CharField(choices=[('TIN', 'Tinned'), ('FRZ', 'Frozen'), ('FRS', 'Fresh'), ('RAW', 'Raw'), ('CKD', 'Cooked'), ('POR', 'Portion'), ('NON', '_')], default='NON', max_length=3, verbose_name='Form')),
                ('foodstuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Foodstuff')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='name',
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='_', unique=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='---', max_length=250, verbose_name='Name of Recipe'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='IngredientList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Quantity')),
                ('uom', models.CharField(choices=[('GRM', 'Grammes'), ('MLT', 'MilliLitres'), ('LTR', 'Litres'), ('UNT', 'Unit'), ('TSP', 'Tea Spoon'), ('TBS', 'Table Spoon'), ('POR', 'Portion'), ('NON', '_')], default='NON', max_length=3, verbose_name='Unit of Measure')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
