# Generated by Django 3.0.12 on 2021-03-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookbooklist',
            name='page',
            field=models.IntegerField(default=0, verbose_name='Page No.'),
        ),
        migrations.AddField(
            model_name='cookbooklist',
            name='url',
            field=models.URLField(default='www.google.com', verbose_name='URL'),
        ),
    ]
