# Generated by Django 3.0.12 on 2021-02-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210225_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredient', through='recipes.IngredientList', to='recipes.Ingredient'),
        ),
    ]
