# Generated by Django 3.0.12 on 2021-03-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210301_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookbooklist',
            name='url',
            field=models.URLField(default='_', verbose_name='URL'),
        ),
    ]
