# Generated by Django 3.0.12 on 2021-02-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['title']},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='form',
            field=models.CharField(choices=[('TIN', 'Tinned'), ('FRZ', 'Frozen'), ('FRS', 'Fresh'), ('RAW', 'Raw'), ('CKD', 'Cooked'), ('POR', 'Portion'), ('CHP', 'Chopped'), ('DCD', 'Diced'), ('SLC', 'Sliced'), ('NON', '_')], default='NON', max_length=3, verbose_name='Form'),
        ),
        migrations.AlterField(
            model_name='ingredientlist',
            name='uom',
            field=models.CharField(choices=[('GRM', 'Grammes'), ('MLT', 'MilliLitres'), ('LTR', 'Litres'), ('UNT', 'Unit'), ('TSP', 'Tea Spoon'), ('TBS', 'Table Spoon'), ('POR', 'Portion'), ('SPL', 'Splash'), ('NON', '_')], default='NON', max_length=3, verbose_name='Unit of Measure'),
        ),
    ]
