# Generated by Django 3.0.12 on 2021-03-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210301_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientlist',
            name='uom',
            field=models.CharField(choices=[('GRM', 'Gram'), ('KGM', 'Kilogram'), ('MLT', 'Millilitre'), ('LTR', 'Litre'), ('TSP', 'Tea Spoon'), ('TBS', 'Table Spoon'), ('DSP', 'Dessert Spoon'), ('UNT', 'Unit'), ('POR', 'Portion'), ('SPL', 'Splash'), ('HND', 'Handfull'), ('NON', '_')], default='NON', max_length=3, verbose_name='Unit of Measure'),
        ),
    ]
