# Generated by Django 3.0.12 on 2021-03-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210303_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='form',
            field=models.CharField(choices=[('TIN', 'Tinned'), ('FRZ', 'Frozen'), ('FRS', 'Fresh'), ('RAW', 'Raw'), ('CKD', 'Cooked'), ('POR', 'Portion'), ('CHP', 'Chopped'), ('DCD', 'Diced'), ('SLC', 'Sliced'), ('MLT', 'Melted'), ('NON', '_')], default='NON', max_length=3, verbose_name='Form'),
        ),
        migrations.AlterField(
            model_name='ingredientlist',
            name='uom',
            field=models.CharField(choices=[('GRM', 'Gram'), ('KGM', 'Kilogram'), ('MLT', 'Millilitre'), ('LTR', 'Litre'), ('TSP', 'Tea Spoon'), ('TBS', 'Table Spoon'), ('DSP', 'Dessert Spoon'), ('UNT', 'Unit'), ('POR', 'Portion'), ('SPL', 'Splash'), ('TST', 'To Taste'), ('HND', 'Handful'), ('NON', '_')], default='NON', max_length=3, verbose_name='Unit of Measure'),
        ),
    ]
