# Generated by Django 3.0.12 on 2021-02-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20210225_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='method',
            field=models.TextField(blank=True, verbose_name='Method'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tag',
            field=models.CharField(blank=True, default='none, ', max_length=100, verbose_name='Tag'),
        ),
    ]
