# Generated by Django 3.0.12 on 2021-02-27 18:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20210225_1308'),
        ('recipes', '0005_auto_20210226_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='name',
            field=models.CharField(blank=True, default='_', max_length=250, verbose_name='Ingredient'),
        ),
        migrations.CreateModel(
            name='CookBookList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Recipe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
