# Generated by Django 3.0.12 on 2021-03-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210304_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookbooklist',
            name='url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='form',
            field=models.CharField(choices=[('TIN', 'Tinned'), ('FRZ', 'Frozen'), ('FRS', 'Fresh'), ('RAW', 'Raw'), ('CKD', 'Cooked'), ('POR', 'Portion'), ('CHP', 'Chopped'), ('DRY', 'Dried'), ('WRM', 'Warm'), ('CLD', 'Cold'), ('DCD', 'Diced'), ('SLC', 'Sliced'), ('MLT', 'Melted'), ('NON', '_')], default='NON', max_length=3, verbose_name='Form'),
        ),
    ]
