# Generated by Django 3.0.12 on 2021-03-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210305_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Cook (mins)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Prep (mins)'),
        ),
    ]
