# Generated by Django 3.0.12 on 2021-02-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20210227_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientlist',
            name='uom',
            field=models.CharField(choices=[('GRM', 'Grammes'), ('MLT', 'Millilitres'), ('LTR', 'Litres'), ('UNT', 'Unit'), ('TSP', 'Tea Spoon'), ('TBS', 'Table Spoon'), ('POR', 'Portion'), ('SPL', 'Splash'), ('NON', '_')], default='NON', max_length=3, verbose_name='Unit of Measure'),
        ),
    ]
