# Generated by Django 3.0.12 on 2021-02-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20210227_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Cook (hrs)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Prep (hrs)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='serves',
            field=models.IntegerField(default=0, verbose_name='Serves'),
        ),
    ]
