# Generated by Django 3.0.12 on 2021-02-15 16:12

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='Title of Book')),
                ('subtitle', models.CharField(max_length=255, verbose_name='Subtitle of Book')),
                ('author', models.CharField(max_length=255, verbose_name='Author(s) of Book')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slug', models.SlugField(default='_', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
