# Generated by Django 3.0.12 on 2021-03-10 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=250, verbose_name='Author Name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type', models.CharField(max_length=25, verbose_name='Book Type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=250, verbose_name='Book Publisher')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=250, verbose_name='Book Title')),
                ('subtitle', models.CharField(blank=True, max_length=250, verbose_name='Subtitle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('isbn', models.CharField(blank=True, max_length=25, verbose_name='ISBN Number')),
                ('pages', models.IntegerField(default=0, verbose_name='No. of Pages')),
                ('form', models.CharField(choices=[('PB', 'Paperback'), ('HB', 'Hardback'), ('KI', 'Kindle'), ('MA', 'Magazine'), ('WL', 'Wishlist'), ('OT', 'Other')], default='OT', max_length=2, verbose_name='Form')),
                ('status', models.CharField(choices=[('RD', 'Completed'), ('RG', 'Reading'), ('TR', 'To read'), ('NT', 'Next'), ('BG', 'Browsing'), ('RE', 'Reference'), ('GU', 'Given-up'), ('WL', 'Wishlist'), ('IA', 'Inactive'), ('UK', 'Unknown')], default='UK', max_length=2, verbose_name='Status')),
                ('slug', models.SlugField(default='_', unique=True)),
                ('tag', models.CharField(blank=True, default='none, ', max_length=100, verbose_name='Tag')),
                ('rating', models.IntegerField(default=0, verbose_name='Rating (1-10)')),
                ('pct_read', models.IntegerField(default=0, verbose_name='Pct% Read')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Author')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Publisher')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.BookType')),
            ],
            options={
                'ordering': ['title', 'subtitle'],
            },
        ),
    ]
