# Generated by Django 3.0.12 on 2021-03-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
