# Generated by Django 3.0.12 on 2021-02-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=25, verbose_name='ISBN Number'),
        ),
    ]
