# Generated by Django 3.0.12 on 2021-02-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210216_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0, verbose_name='No. of Pages'),
        ),
    ]
