# Generated by Django 3.0.12 on 2021-02-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('RD', 'Completed'), ('RG', 'Reading'), ('TR', 'To read'), ('NT', 'Next'), ('BG', 'Browsing'), ('GU', 'Given-up'), ('WL', 'Wishlist'), ('IA', 'Inactive'), ('UK', 'Unknown')], default='UK', max_length=2, verbose_name='Status'),
        ),
    ]
