# Generated by Django 3.0.12 on 2021-03-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210301_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.CharField(blank=True, default='none, ', max_length=100, verbose_name='Tag'),
        ),
    ]
