# Generated by Django 3.0.12 on 2021-03-17 15:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210310_2055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booktype',
            options={'ordering': ['type']},
        ),
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('books', django.db.models.manager.Manager()),
            ],
        ),
    ]
