# Generated by Django 3.0.12 on 2021-02-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210219_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='form',
            field=models.CharField(choices=[('PB', 'Paperback'), ('HB', 'Hardback'), ('KI', 'Kindle'), ('MA', 'Magazine'), ('OT', 'Other')], default='OT', max_length=2, verbose_name='Form'),
        ),
    ]
