# Generated by Django 3.0.12 on 2021-02-17 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210217_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='books.BookType'),
            preserve_default=False,
        ),
    ]
