# Generated by Django 3.0.12 on 2021-02-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pct_read',
            field=models.IntegerField(default=0, verbose_name='Pct% Read'),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Rating (1-10)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='form',
            field=models.CharField(choices=[('PB', 'Paperback'), ('HB', 'Hardback'), ('KI', 'Kindle'), ('MA', 'Magazine'), ('WL', 'Wishlist'), ('OT', 'Other')], default='OT', max_length=2, verbose_name='Form'),
        ),
    ]
