# Generated by Django 3.0.12 on 2021-04-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-date', 'title']},
        ),
    ]
