# Generated by Django 3.0.12 on 2021-04-09 10:56

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210407_1143'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blog',
            managers=[
                ('blog', django.db.models.manager.Manager()),
            ],
        ),
    ]
