# Generated by Django 3.0.12 on 2021-04-07 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210405_1723'),
        ('blog', '0002_auto_20210407_1143'),
    ]

    operations = [
    ]
