# Generated by Django 3.0.12 on 2021-04-14 20:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20210412_2118'),
        ('blog', '0003_auto_20210409_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('blog_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Image')),
                ('blogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='images',
            field=models.ManyToManyField(related_name='blog_image', through='blog.ImageList', to='images.Image'),
        ),
    ]
