# Generated by Django 3.0.12 on 2021-04-09 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_merge_20210407_1330'),
        ('blog', '0003_auto_20210409_1156'),
    ]

    operations = [
    ]
