# Generated by Django 3.0.12 on 2021-02-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210226_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.CharField(blank=True, default='none, ', max_length=100, verbose_name='Tag'),
        ),
    ]
