# Generated by Django 3.0.12 on 2021-04-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210414_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelist',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Ord'),
        ),
    ]
