# Generated by Django 3.0.12 on 2021-04-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_merge_20210409_1100'),
        ('blog', '0004_auto_20210414_2116'),
    ]

    operations = [
    ]
