# Generated by Django 3.0.12 on 2021-04-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_imagelist_order'),
        ('blog', '0005_merge_20210414_2038'),
    ]

    operations = [
    ]
